name: Update TW ISIN to Google Sheets

on:
  schedule:
    # 每週五 01:00 UTC = 台北 09:00
    - cron: "0 1 * * 5"
  workflow_dispatch:   # 手動執行也可以

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install -r requirements.txt

      - name: Run crawler & upload
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          GSHEET_ID: ${{ secrets.GSHEET_ID }}
        run: |
          python main.py